jenkins:
  image: jenkins:alpine
  privileged: false
  ports:
   - "8080:8080"
  volumes:
   - ./jenkins_home:/var/jenkins_home
   - /var/run/docker.sock:/var/run/docker.sock
  links:
   - registry

registry:
  image: registry:2.4
  volumes:
   - ./registry:/var/lib/registry
  ports:
   - "5000:5000"