#!/usr/bin/env bash

set -e

container_name=${PROJECT_NAME}-${BUILD_VERSION}-%i

cat <<EOF
[Unit]
Description=${PROJECT_NAME}
After=network.target

[Service]
User=core
Type=simple
Restart=on-failure
EnvironmentFile=/etc/environment

ExecStartPre=-/usr/bin/docker pull repo.i-nsel.com/${PROJECT_NAME}:${BUILD_VERSION}
ExecStartPre=/usr/bin/bash -c ' \
  for id in \$(docker ps --all --quiet --filter name=${PROJECT_NAME}-${BUILD_VERSION}-*); do \
    docker rm --force \$id; \
  done; \
  '

ExecStart=/usr/bin/docker run --rm \
  --name ${container_name} \
  --env UNIT_NAME=%n \
  --publish \${COREOS_PRIVATE_IPV4}:8080:8080 \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /var/jenkins_home:/var/jenkins_home \
  --volume /var/keys:/var/keys \
  repo.i-nsel.com/${PROJECT_NAME}:${BUILD_VERSION}

ExecStop=/usr/bin/docker stop ${container_name}

[X-Fleet]
Conflicts=${PROJECT_NAME}-${BUILD_VERSION}@*.service
EOF